default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

default_stages:
  - commit
  - push

repos:
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [ black~=23.11 ]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0 # automatically updated by Commitizen
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages:
          - post-commit
          - push

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        name: Run codespell to check for common misspellings in files
        language: python
        types: [ text ]
        args: [ "--write-changes", "--ignore-words-list", "asend" ]
        exclude: "poetry.lock"

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py312-plus
        types: [python]
        language: system

      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: poetry run isort pyarr
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: poetry run black pyarr --check
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: poetry run flake8 pyarr
        types: [python]
        exclude: setup.py

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: poetry run mypy pyarr
        types: [python]
        pass_filenames: false
